Fix compiler warning
This fixes the following warning:

In file included from /usr/include/stdlib.h:24:0,
                 from texcaller.h:172,
                 from texcaller.c:14:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~